# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
    - release

install: travis_wait mvn install

addons:
   apt:
     packages:
       - r-cran-ggplot2
       - r-cran-nlme
       - r-cran-gdata
       - r-cran-hnp
       - r-cran-utils
       - r-cran-stats
       - r-cran-grid
       - r-cran-gridExtra

r_build_args: --no-build-vignettes
r_check_args: --no-vignettes

notifications:
   email:
     on_success: change
     on_failure: change
     
after_success:
    - Rscript -e 'covr::codecov()'
