# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev
  - sudo apt-get install maven

r: devel

install: travis_wait mvn install

addons:
   apt:
     packages:
       - r-cran-ggplot2
       - r-cran-nlme
       - r-cran-gdata

r_build_args: --no-build-vignettes
r_check_args: --no-vignettes

notifications:
   email:
     on_success: change
     on_failure: change
     
after_success:
    - travis_wait Rscript -e 'library(covr); codecov()'

branches:
  only:
    - master
