
## https://docs.travis-ci.com/user/languages/r/

language: r
sudo: false
matrix:
  include:
    - name: "Roxygen check"
      r: release
      r_packages:
        - devtools
        - covr
        - ggplot2
        - nlme
        - gdata
        - hnp
        - utils
        - grid
      cache: packages
    - r: 3.4
    - r: 3.5
    - r: release

## this saves time; it also stops us from getting R CMD check warnings
## (which get promoted to errors/build failures unless we specify
## "warnings_are_errors: false" here ...)
r_build_args: "--no-build-vignettes"

## need travis_wait because checks take 10+ minutes ...
after_success:
  - travis_wait Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master




